### ISSUE TITLE
Muy agradecido por tu código

### ISSUE THREAD

**Issue by arsendm** [joseayram/utils#1]
Hola José, espero todo marche bien.

Generalmente uno no escribe para agradecer por el código útil que consiguimos en internet. Está increíblemente ordenado y muy bien hecho. 

He estado haciendo unas pruebas y algunas veces aparece el error de "Sin Conexión a Internet" y otras si funciona perfectamente. Me imagino que la plataforma del SENIAT no debe ser muy estable.

Muy agradecido.

Saludos,

**Comment by joseayram** [comment]
Gracias a ti por tomarte un tiempo en escribir. Espero te siga siendo de utilidad, cualquier aporte que puedas hacer para mejorarlo será bien recibido. Saludos.
