### ISSUE TITLE
RIF de Consejos Comunales

### ISSUE THREAD

**Issue by dilworks** [joseayram/utils#3]
A partir de Agosto del 2015, se introdujo la letra "C" para los RIF de Consejos Comunales, y de hecho todos aquellos con RIF preexistente (que en su caso comenzaba con "J") fueron migrados a nuevos RF con la letra C.

He aqui un ejemplo real:
http://i1.wp.com/elestimulo.com/wp-content/uploads/2015/08/IMG_7986_1.jpg
Si lo consultamos en el SENIAT, nos da esto:

> C406400572 EMPRESA DE PROPIEDAD SOCIAL DIRECTA GRAN COMUNAL DE TRANSPORTE SENDEROS DE HUGO CHAVEZ (NO INDICA)
> 
> Actividad Económica: TRANSPORTE TERRESTRE DE PASAJEROS DEL AREA URBANA, SUBURBANA O METROPOLITANA
> 
> La condición de este contribuyente requiere la retención del 100% del impuesto causado, salvo que esté exento, no sujeto o demuestre ante el Agente de Retención del IVA que es un contribuyente exonerado.

Pero como de costumbre y para variar, el sitio del SENIAT no da mayores detalles sobre el valor correspondiente a la letra C en el algoritmo de validación. Intente asignándole el 6 (que seria el que debería corresponderle), pero el checksum me da 1, no 2. Por pura curiosidad cambie la C por la J que antes les correspondía y sorpresa sorpresa: el checksum es valido!

Me resulta curioso que no le hayan asignado un peso a la letra C -  simplemente la convirtieron en un alias para la J. Eso se puede prestar para confusiones en un futuro, pero por ahora hay que considerar ese detalle. Ahora, si alguien tiene mas ejemplos de RIFs reales para consejos comunales, podrían ayudar a confirma mi teoria.

**Comment by dilworks** [comment]
Bien, conseguí el RIF de otro consejo comunal aun con J (J-40101223-0), lo comprobé en la pagina del SENIAT cambiándole la J por la C, y en efecto es valido (si lo buscas con la J no sale, indicativo de que ya fue migrado).

Que indica esto? Para propósitos de validación, **la C es un alias para la J**.

**Comment by joseayram** [comment]
¡Hola @dilworks! Gracias por el comentario.

Es decir, que valdría el mismo dígito especial para ambas letras C y J ¿Cierto?

Puedes enviar el PR o apenas tenga oportunidad realizo la actualización correspodiente.

Muchas gracias de antemano.
