### ISSUE TITLE
Space required after the Public Identifier

### ISSUE THREAD

**Issue by ric128** [joseayram/utils#4]
Estimado José
Después de funcionar muy bien durante un tiempo he empezado a recibir este error en la línea 87

simplexml_load_string(): Entity: line 1: parser error : Space required after the Public Identifier

Espero que tenga solución.
Saludos.

**Comment by joseayram** [comment]
¡Hola @ric128! 

Lamentablemente el Senia la url que usaba la librería para consultar está caída desde hace algunas semanas y hasta ahora no tengo idea de si será algo temporal.

**Comment by ric128** [comment]
Gracias por tu respuesta.
Supuse que sería un problema del SENIAT.

No sería mala idea "controlar" el error para que los usuarios finales reciban un mensaje del tipo "Portal del SENIAT inactivo" o algo así.

Gracias por tu ayuda.

**Comment by joseayram** [comment]
@ric128 Totalmente de acuerdo. Apenas tenga un respiro hago el cambio, pero igual al no ser un paquete vía composer los usuarios que la estén utilizando no sabrán de la actualización :(.

**Comment by ric128** [comment]
No creo que sea un problema. 
Al ver el error lo primero que hice fue entrar a github y reemplazar el codigo manualmente.
Ya eso es responsabilidad de cada desarrollador sabiendo que tú no actualizas vía composer.

**Comment by joseayram** [comment]
@ric128 Agregado el cambio. Gracias por el reporte.

**Comment by ric128** [comment]
Gracias por el esfuerzo. Ahora se ve más prolijo.
Corrije "innaccesible" que te quedó con doble n.
Saludos cordiales.

**Comment by joseayram** [comment]
Gracias a ti @ric128. Listo el error de typo. Saludos.
