### ISSUE TITLE
Seniat Not Found

### ISSUE THREAD

**Issue by marcoadasilvaa** [joseayram/utils#5]
Saludos Jose

Has encontrado alguna alternativa a la URL [Seniat](http://contribuyente.seniat.gob.ve/getContribuyente/getrif?rif=) ya que desde hace algunos meses no esta operativa:

Not Found
The requested URL /getContribuyente/getrif was not found on this server.

Saludos!

**Comment by joseayram** [comment]
No, ninguna @markmarco16 por ahora.
